name: GitHub Pages Deployment

on:
  push:
    branches:
      - main  # Run workflow on push to main branch
  workflow_dispatch:  # Allow manual workflow runs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify file structure
        run: |
          echo "Repository content:"
          ls -la
          echo "Data directory content:"
          ls -la data/

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: .  # Deploy project root

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read
  pages: write
  id-token: write
